# Generated by Django 3.1.4 on 2020-12-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('cabinet_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер кабинета')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('workplace_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер рабочего места')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='booking.cabinet', verbose_name='Кабинет')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(verbose_name='Дата начала бронирования')),
                ('datetime_to', models.DateTimeField(verbose_name='Дата окончания бронирования')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='booking.workplace', verbose_name='Рабочее место')),
            ],
        ),
    ]
