# Generated by Django 3.1.4 on 2020-12-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('number', 'cabinet')},
        ),
    ]
