# Generated by Django 3.1.4 on 2020-12-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201225_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='datetime_from',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='datetime_to',
        ),
        migrations.AlterField(
            model_name='booking',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='booking.workplace', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to='booking.cabinet', verbose_name='Кабинет'),
        ),
    ]
