# Generated by Django 3.1.4 on 2020-12-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201225_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together=set(),
        ),
    ]
