# Generated by Django 3.1.4 on 2020-12-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20201225_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('workplace_number', 'cabinet')},
        ),
    ]
