# Generated by Django 3.1.4 on 2020-12-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_workplace', to='booking.workplace', verbose_name='Рабочее место'),
        ),
    ]
